force-app/main/default/objects/DownladCount__c/DownladCount__c.object-meta.xml
<CustomObject>
    <label>DownladCount</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>DownladCount Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DownladCounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DownladCount__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DownladCount__c/fields/MetaData_Id__c.field-meta.xml
<CustomField>
    <fullName>MetaData_Id__c</fullName>
    <label>MetaData Id</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/index_value__mdt/index_value__mdt.object-meta.xml
<CustomObject>
    <label>indexvalue</label>
    <pluralLabel>indexvalues</pluralLabel>
</CustomObject>

force-app/main/default/objects/index_value__mdt/fields/actionName__c.field-meta.xml
<CustomField>
    <fullName>actionName__c</fullName>
    <label>actionName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/apiName__c.field-meta.xml
<CustomField>
    <fullName>apiName__c</fullName>
    <label>apiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LWC</fullName>
                <default>true</default>
                <label>LWC</label>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/Discription__c.field-meta.xml
<CustomField>
    <fullName>Discription__c</fullName>
    <label>Discription</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/Download__c.field-meta.xml
<CustomField>
    <fullName>Download__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Download</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/DownloadURL__c.field-meta.xml
<CustomField>
    <fullName>DownloadURL__c</fullName>
    <label>DownloadURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/objectApiName__c.field-meta.xml
<CustomField>
    <fullName>objectApiName__c</fullName>
    <label>objectApiName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/Run__c.field-meta.xml
<CustomField>
    <fullName>Run__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/RunURL__c.field-meta.xml
<CustomField>
    <fullName>RunURL__c</fullName>
    <label>RunURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <label>type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/index_value__mdt/fields/viewCount__c.field-meta.xml
<CustomField>
    <fullName>viewCount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>viewCount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/indexPageController.cls
public with sharing class indexPageController {
    @AuraEnabled(cacheable=true)
    public static List<index_value__mdt> getMataDataList(){
        try {
            return[
                SELECT 
                Id,
                Category__c,
                Discription__c,
                Download__c,
                DownloadURL__c,
                Run__c,
                RunURL__c,
                actionName__c,
                apiName__c,
                objectApiName__c,
                type__c,
                viewCount__c
                FROM index_value__mdt
                ORDER BY Run__c ASC 
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<DownladCount__c> viewCount(Id recordId){
        System.debug('*****'+recordId);
        try {
            return[
                SELECT 
                Id,
                Count__c,
                MetaData_Id__c
                 FROM DownladCount__c
                Where MetaData_Id__c =: recordId
                
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    

    @AuraEnabled(cacheable=false)
    public static void updateData(Id rowIdCount){
        system.debug('rowIdCount+++'+rowIdCount);
        try {
            List<DownladCount__c> updateDownloadCount = new List<DownladCount__c>();
            List<DownladCount__c> updateDownCountRecord = new List<DownladCount__c>();
            updateDownloadCount = [SELECT Id,
                Count__c,
                MetaData_Id__c
                FROM DownladCount__c
                Where MetaData_Id__c =: rowIdCount];
            if(updateDownloadCount.size()>0){
                for(DownladCount__c dc : updateDownloadCount){
                    dc.Count__c = dc.Count__c + 1;
                    updateDownCountRecord.add(dc);
                }
                update updateDownCountRecord;
            }
            else{
                DownladCount__c dcNewRecord = new DownladCount__c();
                dcNewRecord.Count__c = 1;
                dcNewRecord.MetaData_Id__c = rowIdCount;
                //updateDownCountRecord.add(dcNewRecord);
                insert dcNewRecord;

            }
            system.debug('updateDownCountRecord'+ Limits.getLimitDMLStatements());
            if (Limits.getDMLStatements() >= Limits.getLimitDMLStatements()) {
                //upsert updateDownCountRecord;
                // Handle the situation where you are reaching the DML statement limit
            }
            // if(updateDownCountRecord.size()>0){
                

            // }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}