force-app/main/default/objects/Innovation__c/Innovation__c.object-meta.xml
<CustomObject>
    <label>Innovation</label>
    <nameField>
        <label>Innovation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Innovation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Innovation__c/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <label>Domain</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Medical</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Innovation__c/fields/Fund__c.field-meta.xml
<CustomField>
    <fullName>Fund__c</fullName>
    <label>Fund</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Innovation__c/fields/Stages__c.field-meta.xml
<CustomField>
    <fullName>Stages__c</fullName>
    <label>Stages</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ideation &amp; Idea Generation</fullName>
            </value>
            <value>
                <fullName>Evaluation</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Development &amp;Implementation</fullName>
            </value>
            <value>
                <fullName>Optimization &amp; Scaling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InnovationStatsController.cls
public class InnovationStatsController {
	@AuraEnabled
    public static List<Innovation__c> getInnovList(){
        List<Innovation__c> InnovList = new List<Innovation__c> ([ select id, Name,Domain__c, Fund__c,Start_Date__c,Stages__c  from Innovation__c ]);
        return InnovList;
    }
    
    @AuraEnabled
    public static List<Innovation__c> updatedRecords(List<Innovation__c> recordsToUpdate){
        update recordsToUpdate;
        return recordsToUpdate;
    }
    
        @AuraEnabled
    public static List<Innovation__c> fetchRecords(String searchWord){
        String modifiedKeyWord =  searchWord + '%';
        List<Innovation__c> fetchedList = new List<Innovation__c> ([ SELECT id, Name,Domain__c, Fund__c,Start_Date__c,Stages__c  FROM Innovation__c WHERE Name LIKE :modifiedKeyWord]);
        return fetchedList;
    }
}